server:
  port: 8080

spring:
  application:
    name: Task Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: kratik_super_user
    password: Qwerty@0902
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gargkratik083@gmail.com
    password: lsycvjhdrguuuvpj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true